### ISSUE TITLE
Getting json response from query?

### ISSUE THREAD

**Issue by zemian** [nalgeon/sqlime#1]
Hi, I like your project. It's simple and easy to use and explore data. I was wondering, would be possible to allow query result to return pure JSON instead of html table? It would be nice to make it consumable from a REST client.

Thanks,
Zemian

**Comment by nalgeon** [comment]
Hello Zemian! Thanks for your feedback! sqlime is a client-only app, there is no server. You won't be able to call it via REST at all. It's meant for humans only ツ

**Comment by zemian** [comment]
Oh okay, no problem. Thanks for the quick reply. I still like your work. It's nice and simple on the client indeed.
It's amazing how one can trans-compile C code into JS. You have put it to good use :)
