### ISSUE TITLE
Feature Request: Clear data if zero rows returns

### ISSUE THREAD

**Issue by fey** [nalgeon/sqlime#14]
It would be good to show empty table if 0 rows found.

Example:
1. Try demo db
2. Run query `select * from employees;`. See 10 rows.
3. Run query `select * from employees WHERE name = 'test'`;. You still see 10 rows.

Perhaps the query output should always be cleared before execution.

**Comment by nalgeon** [comment]
I agree wholeheartedly! Done in [3db274a](https://github.com/nalgeon/sqlime/commit/3db274a2be139b1cec47f537ee1d380334cae54d).
