### ISSUE TITLE
select query with the duplicate column names does not work correctly

### ISSUE THREAD

**Issue by fey** [nalgeon/sqlime#15]
We have query: 
```
select sales.dat, calendar.dat
from sales
left join calendar
on sales.dat = calendar.dat
order by 1 nulls first, 2 nulls first
```

But we see only 1 column 

![image (5)](https://user-images.githubusercontent.com/697178/234334574-26d7d6e5-5759-497b-b7cf-75f55b17bfe0.png)

Example from DBeaver (sqlite db engine)

![image](https://user-images.githubusercontent.com/697178/234334809-c03e3e28-7cae-4ab6-8ce5-d39482e2c11f.png)

**Comment by nalgeon** [comment]
This is by design. SQLite returns a single column in this case. Use column aliases:

```sql
select sales.dat as dat1, calendar.dat as dat2
from sales
```
