### ISSUE TITLE
Dot commands are given as SQL errors

### ISSUE THREAD

**Issue by coatless** [nalgeon/sqlime#17]
First, thank you for the awesome integration with SQLite's WASM.

Second, I'm trying to understand where to place this issue. 

The main hiccup is the WASM interpreter seems to not like [SQLite's dot commands](https://www.sqlite.org/cli.html#special_commands_to_sqlite3_dot_commands_), e.g.

```sh
sqlite> .tables
```

```
SQLite3Error: sqlite result code 1: near ".": syntax error
```

Is there any way to use the dot commands within the extension?

**Comment by nalgeon** [comment]
This is by design. Dot commands are not part of the SQLite database engine; they are only supported in the SQLite command line interface (CLI). SQLite CLI is not available in WASM build.

**Comment by coatless** [comment]
@nalgeon thanks for the clarity on that. I suppose I thought dot commands would be available since [DuckDB's WASM](https://github.com/duckdb/duckdb-wasm) provides that option on their [shell emulator](https://shell.duckdb.org/).

That said, the interface that you designed is phenomenal and was recently wrapped into a [quarto extension called `{interactive-sql}`](https://github.com/shafayetShafee/interactive-sql).

One quick question for you: From a quick glance through the code base, if I wanted to swap out the underlying `Engine` to say `DuckDB`, [`PostgreSQL`](https://github.com/snaplet/postgres-wasm), or another SQL variant, I would mainly need to re-implement portions of logic at:

<https://github.com/nalgeon/sqlime/tree/main/js/sqlite>
