### ISSUE TITLE
feat: improve query editor

### ISSUE THREAD

**Issue by jlarmstrongiv** [nalgeon/sqlime#18]
- Add SQLITE syntax highlighting
- Allow tabs to add space/tabs in the editor, not focus the run button

Really cool project 😄 thank you for open sourcing—it’s one of the few examples I’ve found with SQLITE WASM

**Comment by nalgeon** [comment]
Thank you! I've added tabs-to-spaces conversion (tab = 2 spaces). Unfortunately, I'm strongly against syntax highlighting, so I won't add it.
