### ISSUE TITLE
Not obvious when running SQL if it's updated.

### ISSUE THREAD

**Issue by buckett** [nalgeon/sqlime#19]
When experimenting with SQL in the browser after clicking "Run" the results are updated pretty much instantly for me. This is great, but it means it's sometimes not obvious that the results have been updated (eg if the result is still the same). It's great that it's fast, however I wonder if adding a tiny pause ( & maybe spinner display) and only then setting the output (eg 100ms), so there is a clue that the results have been refreshed, but it doesn't get in the way of quickly iterating on the SQL.

**Comment by buckett** [comment]
An alternative would be to include a prefix to the results (eg timestamp, result count, transation id) which changes between runs.

**Comment by nalgeon** [comment]
Thank you! I've stumbled across this too, but was too lazy to fix it unless someone complained :) Now I've added a short fade in/out animation.

Implemented in both [playground](https://sqlime.org/) and widget [0.1.5](https://www.npmjs.com/package/sqlime/v/0.1.5) (+ [widget demo](https://sqlime.org/examples.html)).

**Comment by buckett** [comment]
Thanks, nice work.
