### ISSUE TITLE
Feature Request: Take DB URL to load in the host url

### ISSUE THREAD

**Issue by assayire** [nalgeon/sqlime#20]
It would be handy if we can use https://sqlime.org?db=https%3A%2F%2Fraw.githubusercontent.com%2Fnalgeon%2Fsqlime%2Fmain%2Femployees.db to load the db at the url specified on start

**Comment by nalgeon** [comment]
You can do that: https://sqlime.org/#https://raw.githubusercontent.com/nalgeon/sqlime/main/employees.db
