### ISSUE TITLE
Support larger >1GB sqlite databases

### ISSUE THREAD

**Issue by jlarmstrongiv** [nalgeon/sqlime#21]
### ArrayBuffer limitations

Currently, SQLite databases are loaded using arraybuffers:
 
- ```js
  response.arrayBuffer();
   ```
- ```js
  function loadDbFromArrayBuffer(buf) { … }
  ```

Arraybuffers have limited sizes:
- Chrome 2145386496 bytes is 2.145386496 gb
- Safari 4294967296 bytes is 4.294967296 gb
- Firefox 8589934592 bytes is 8.589934592 gb

### String limitations

Or by loading text:
- ```js
  return response.text();
  ```

Strings have limited sizes:
- Chrome 1073741776 bytes is 1.073741776 gb
- Safari 4294967294 bytes is 4.294967294 gb
- Firefox 2147483644 bytes is 2.147483644 gb

## Solutions

### [Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API) / [Web Streams API](https://nodejs.org/api/webstreams.html)

To handle larger files, it is possible to use Web Streams:

- [With](https://developer.chrome.com/articles/fetch-streaming-requests/) [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams)
  ```js
  // request
  await fetch(url, {
    body: new ReadableStream()
  })
  // response
  const readable = (await fetch(url)).body
  ```
- With the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createWritable)
  ```js
  const writable = await fileHandle.createWritable();
  const readable = (await fileHandle.getFile()).stream();
  ```
  

### [WebAssembly.Memory](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory)

A [workaround](https://bugs.chromium.org/p/chromium/issues/detail?id=1201109) to creating a larger array buffer is using [`new WebAssembly.Memory`](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/Memory)

However, I think using the Streams API is a better fit.

### Other

I was looking at the [implementation](https://github.com/nalgeon/sqlime/blob/main/js/sqlite/manager.js#L200-L213):
```js
function loadDbFromArrayBuffer(buf) {
    const bytes = new Uint8Array(buf);
    const p = sqlite3.wasm.allocFromTypedArray(bytes);
    const db = new sqlite3.oo1.DB();
    sqlite3.capi.sqlite3_deserialize(
        db.pointer,
        "main",
        p,
        bytes.length,
        bytes.length,
        sqlite3.capi.SQLITE_DESERIALIZE_FREEONCLOSE
    );
    return db;
}
```

And I’m thinking that if [OPFS VFS support](https://sqlite.org/wasm/doc/trunk/persistence.md#vfs-opfs) is active, then we can stream the db file to the OPFS VFS, and then open the DB from the file we created.

Using OPFS requires cross-origin isolation ([COOP and COEP](https://web.dev/coop-coep/)), which can be added to GitHub pages with [coi-serviceworker](https://github.com/gzuidhof/coi-serviceworker).

**Comment by nalgeon** [comment]
Thanks for the suggestion! This project is a playground for working with _snippets_ of SQL code. It does not support large databases by design, and probably never will. At least not until I have a _very_ compelling reason to spend a week of my time implementing that support.
