### ISSUE TITLE
Exporting database as sqlite3 file (or raw gist ?)

### ISSUE THREAD

**Issue by agademer** [nalgeon/sqlime#23]
First, thank you for this wonderful open-source tool !

I'm a teacher and I would like to use Sqlime in my courses (to teach them basic CRUD operations) but I would need the students to be able to export their database at the end of the lab.
For the moment they could "Share" it with me but : 
 - It is unclear were the data is sent/stored (your message say "Public cloud", investigating the code shows a Deta cloud but Deta website is quite opaque)
 - I would like to be able to get the data "out" of sqlime at some point.

**Would it be possible to add an "export" option were the data is downloaded as sqlite3 file ?**

A raw gist format (or just the schema.sql part) would be acceptable also even if a sqlite3 format would be better because it would allow to reload it later in input of Slime3 :)

Thanks you in advance for considering my case.

(Hint on how to modify your code by myself could also be cool if you don't have plan to do it yourself)

Kind regards

Antoine

**Comment by nalgeon** [comment]
Hey Antoine, thanks for your interest in Sqlime! It already stores the database as a GitHub gist. All you have to do is set your GitHub credentials in the [settings](https://sqlime.org/settings.html).

**Comment by agademer** [comment]
Thanks for your quick answer.

I had not understood how it worked.

I just tried and it could work for my use case (with my teacher gist API
key).

Thanks again for the great tool.

Kind regards
