### ISSUE TITLE
COOP & COEP headers

### ISSUE THREAD

**Issue by hbi99** [nalgeon/sqlime#25]
At [sqlime.org](https://sqlime.org/), the console is warning "_Ignoring inability to install OPFS sqlite3_vfs_".

![image](https://github.com/user-attachments/assets/e63d6247-5d3f-44b2-a47b-ff38e32d0864)

Is this due to some changes on your server? I assume this was not an issue earlier and everything "worked" as intended. It is also possible Chrome changed some policies since your launch `¯\_ (ツ)_/¯`

Anywho, in my development environment, I have fixed the headers so that the COOP & COEP headers are served as suggested [here](https://sqlite.org/wasm/doc/trunk/persistence.md#coop-coep)..._see screenshot below_. Despite that, I am getting the same warning. Do you have any suggestions?

Thanks in advance

![image](https://github.com/user-attachments/assets/24acb069-2e7e-4e6a-8b1a-f4f8ebd1ec66)

**Comment by nalgeon** [comment]
sqlime.org is hosted by GitHub Pages, which does not support SharedArrayBuffer (missing COOP/COEP headers), hence the warning. This does not affect the functionality of the playground — everything works fine.

I can't comment on your local setup, unfortunately. Could be an insecure context or something else. See the MDN article for a detailed explanation of the [SharedArrayBuffer requirements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer).

**Comment by hbi99** [comment]
I do have other WASM solutions served from same dev-env, requiring SharedArrayBuffer. This do work fine. Sqlite3.wasm does not. I wonder, does this warning go away in any environment?

Cheers

**Comment by nalgeon** [comment]
No idea, sorry. I'm not really interested in using OPFS at the moment, so I'd rather not investigate.
