### ISSUE TITLE
ability to embed sqlime in an article without the article scrolling?

### ISSUE THREAD

**Issue by daniellacosse** [nalgeon/sqlime#26]
Hello there! I'm currently working on a little gallery of various web technologies and I want to embed sqlime into it! However, since the editor focuses itself on load, my article automatically scrolls to it no matter what I do 😅 

Perhaps I could add a querystring parameter to the page that disables the focus if it is set? (e.g. `?disable_form_focus=1`) Happy to submit a PR if this is something you'd support.

**Comment by nalgeon** [comment]
Hi Daniel! Sqlime is not meant for embedding, but you can use [Codapi](https://github.com/nalgeon/codapi-js) for that.
