### ISSUE TITLE
Multiple results?

### ISSUE THREAD

**Issue by fowl2** [nalgeon/sqlime#28]
Currently, if I have a query / multiple queries that return more than one result, only the first is shown. It would be great if all would be shown, in seperate tables, with runtimes and counts etc.

![image](https://github.com/user-attachments/assets/080d048f-35af-4658-8a8e-afc4fb13f9ab)

**Comment by fowl2** [comment]
I had a look through the [sqlite api](https://sqlite.org/wasm/doc/trunk/api-oo1.md#db-exec) and it looks like this is non-trivial to get right.

I [posted on the sqlite forum](https://sqlite.org/forum/info/2b8b7cbc5a916933) to see if I missed something / perhaps they have any suggestions.

**Comment by nalgeon** [comment]
Sorry, no current plans for multiple results.
