### ISSUE TITLE
Saving a link to web hosted database rather than the downloaded database

### ISSUE THREAD

**Issue by psychemedia** [nalgeon/sqlime#6]
This a really handy app - thanks for sharing. :-)

I note that if a user wants to query a web hosted SQLite database, the whole database is downloaded into the browser and then queried in-memory.

When a Github credentialled user shares a query, both the query and the database seem to be saved as a (private) gist. If the user saves a lot of queries, this is quite wasteful in terms of resource (network, gist storage).

It would be convenient in such cases if the user could:

- choose to save either the full db or the remote URL to the gist;
- when loading from the gist, chec to see if the full db or the remote URL is specified:
  - if the full db / sql code is provided, load that, as is currently the case;
  - if a remote URL is specified for the database, check to see if the current loaded database has been loaded from the same remote URL; if it has, retain the current database and just load the query in the gist; if the current loaded database has a different source to the remote specified URL, replace the database with a connection to a new database downloaded from the remote URL.

**Comment by nalgeon** [comment]
Thanks! I believe that load / save logic is complex enough as it is, and there is no need to complicate if further. Using gists is fine with me.
