### ISSUE TITLE
Support connections to remotely hosted sqlite databases

### ISSUE THREAD

**Issue by psychemedia** [nalgeon/sqlime#7]
If a web hosted database is large, the user may not want to download it into memory. The [`phiresky/sql.js-httpvfs`](https://github.com/phiresky/sql.js-httpvfs) fork of `sql.js` "provide[s] a read-only HTTP-Range-request based virtual file system for SQLite" (see also: [Hosting SQLite databases on Github Pages (or any static file hoster)](https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/)).

This means that queries can be run against an arbitrarily large remotely hosted sqlite database without taking the hit of having to download the whole database.

It would be useful if SQLime could offer a similar facility in the form a connection to a remote database.

When sharing a query, if the remote URL rather than the database export could be saved to the gist (eg https://github.com/nalgeon/sqlime/issues/6 ), then on loading from a gist, the user could be prompted to as to whether they want to download the database into memory, or set up a remote connection to it.

**Comment by nalgeon** [comment]
One probably should not use JSFiddle for production development of JavaScript applications. Similarly, SQLime does not try to be a UI for working with large databases. It is specifically intended for small snippets of SQL code. I do not plan to support database streaming via HTTP or any other means of loading large databases.
