### ISSUE TITLE
Sqlitewasm

### ISSUE THREAD

**Issue by gedw99** [nalgeon/sqlime#8]
You could use SQLite wasm.
It uses the file system api of the browser which is now even available in iOS safari 

https://www.phoronix.com/news/SQLite-3.40-Released

**Comment by nalgeon** [comment]
SQLime was always working on iOS. Now I've switched from sql.js to the official WASM build — let's see how it goes.

**Comment by mingodad** [comment]
Also there is this https://github.com/mingodad/CG-SQL-Lua-playground that uses https://github.com/facebookincubator/CG-SQL and `Lua`.

**Comment by gedw99** [comment]
> SQLime was always working on iOS. Now I've switched from sql.js to the official WASM build — let's see how it goes.

Cool stuff . Will be interesting to see perf differences

**Comment by nalgeon** [comment]
The official WebAssembly build works fine, I don't plan to do anything more here. I've even managed to build it [with extensions](https://github.com/nalgeon/sqlean.js).
