### ISSUE TITLE
Run only selected query from the editor

### ISSUE THREAD

**Issue by tushartambe** [nalgeon/sqlime#9]
Hello, Currently when we hit run button all the text in editor is evaluated and executed. 
If only selected query is executed it will help all of users maintain short history and run queries faster.

**Comment by tushartambe** [comment]
```
const selectedQuery = window.getSelection().toString();
  this.dispatchEvent(
       new CustomEvent("execute", {detail: selectedQuery === "" ? this.value : selectedQuery})
);
```

This small piece of code will do the work as well

**Comment by nalgeon** [comment]
Thanks, I really like the idea! Will check it out when I have some time.

**Comment by buckett** [comment]
Splitting on SQL statements is a nice feature of other interactive SQL tools, where you can select to run the SQL statement under the cursor, or everything in the whole scratch area/file. However then SQLime would have to be able to parse the SQL and work out where a SQL statement starts and ends, just searching for semicolons would fail on:
`insert ';' into table;`

**Comment by nalgeon** [comment]
I believe that in the context of this question 'selected query' means literally selected part of the text, not the query under the cursor. So there is no need for parsing.

**Comment by tushartambe** [comment]
@nalgeon thats what I intended.

**Comment by nalgeon** [comment]
Done! Now one can select a part of the query in the editor and run it using Cmd/Ctrl + Enter or the Run button.
